LocalSocket /run/clamav/clamd.sock
FixStaleSocket yes
LocalSocketMode 666
DatabaseDirectory /var/lib/clamav
LogFile /var/log/clamav/clamd.log
LogTime yes
User clamav
MaxScanSize 50M
MaxFileSize 25M
MaxRecursion 10
MaxFiles 1000
StreamMaxLength 25M
